backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "jobs"
    label: "Job Gallery"
    folder: "data/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Job Name", name: "title", widget: "string" }
      - { label: "Job Category", name: "category", widget: "select", options: ["Repair", "Install", "Maintenance", "Custom"] }
      - { label: "Job Photos", name: "images", widget: "image", multiple: true }
      - { label: "Description", name: "description", widget: "text", required: false }
